---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- resources:
  - events
  verbs:
  - create
  - patch
- resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  - certificatesigningrequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - sampleclusterissuers.sample-issuer.example.com/*
  resources:
  - signers
  verbs:
  - sign
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers
  - sampleissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers/status
  - sampleissuers/status
  verbs:
  - patch
